-- SQL PRACTICE (for my project portfolio)
--
-- Challenge 2: READ - Data Analysis Query
-- 
-- Scenario: Build a report showing user activity. Return:
-- - User email and username
-- - Total receipts per user
-- - Average receipt total per user
-- - Most recent receipt date per user
-- - Store name that appears most often per user
-- 
-- Requirements:
-- - ORDER BY total receipts descending
-- - LIMIT to top 10 users