-- Challenge 1: CREATE - Test Data Setup
-- 
-- Scenario: Create 50 test receipts for a user. Requirements:
-- - Use a single INSERT with a subquery to get the user_id
-- - Store names: "Walgreens", "Kwik Trip", "Target" (rotate evenly)
-- - Totals between $15.00 and $150.00
-- - Purchase dates spread over the last 3 months
-- - At least 20% marked as favorites
-- - Use nested SELECT to ensure the user exists before inserting
-- 
-- Constraints: One INSERT statement. No loops or functions.
