name: CI

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  jest-tests:
    uses: ./.github/workflows/jest.yml
    secrets: inherit

  ui-tests:
    needs: jest-tests
    uses: ./.github/workflows/playwright-ui-tests.yml
    secrets: inherit