name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  packages: read

jobs:
#   api-tests:
#     uses: ./.github/workflows/playwright-api-tests.yml

  ui-tests:
    # needs: api-tests
    uses: ./.github/workflows/playwright-ui-tests.yml
    secrets: inherit